#all professors
INSERT INTO professors(name,department) VALUES ("Sandra Clarkson", "Math and Statistics");
ALTER TABLE professors AUTO_INCREMENT = 5000;

INSERT INTO professors(name,department) VALUES ("Sandra Clarkson", "Math and Statistics");
INSERT INTO professors(name,department) VALUES ("Amelia Sachs", "Language");
INSERT INTO professors(name,department) VALUES ("Rick Sellitto", "Science");
INSERT INTO professors(name,department) VALUES ("Max Cadman", "History");
INSERT INTO professors(name,department) VALUES ("Lincoln Rhyme", "Criminal Justice");
INSERT INTO professors(name,department) VALUES ("Rachel Sachs", "Arts and Music");
INSERT INTO professors(name,department) VALUES ("Alison Bailey", "Language");
INSERT INTO professors(name,department) VALUES ("Cole Lockhart", "Law");
INSERT INTO professors(name,department) VALUES ("Peter Taylor", "Business");
INSERT INTO professors(name,department) VALUES ("Martin Solloway", "Math and Statistics");
INSERT INTO professors(name,department) VALUES ("Eric Castillo", "Science");
INSERT INTO professors(name,department) VALUES ("Janelle Wilson", "Business");
INSERT INTO professors(name,department) VALUES ("Joanie Lockhart", "Criminal Justice");
INSERT INTO professors(name,department) VALUES ("Luisa Lesin", "Math and Statistics");
INSERT INTO professors(name,department) VALUES ("Oscar Hodges", "Law");
INSERT INTO professors(name,department) VALUES ("Sasha Mann", "History");
INSERT INTO professors(name,department) VALUES ("Kevin Richardson", "Language");
INSERT INTO professors(name,department) VALUES ("Bobby McCray", "Arts and Music");
INSERT INTO professors(name,department) VALUES ("Howard Diller", "Language");
INSERT INTO professors(name,department) VALUES ("Molly Strand", "English");
INSERT INTO professors(name,department) VALUES ("Raymond Santana", "Business");
INSERT INTO professors(name,department) VALUES ("Ruth Deaver", "Language");
INSERT INTO professors(name,department) VALUES ("Joy Wilkes", "English");
INSERT INTO professors(name,department) VALUES ("Chris Merrill", "Law");
INSERT INTO professors(name,department) VALUES ("Matias Reyes", "English");
INSERT INTO professors(name,department) VALUES ("Peter Rivera", "Law");
INSERT INTO professors(name,department) VALUES ("Theresa Porter", "Math and Statistics");
INSERT INTO professors(name,department) VALUES ("Nancy Ryan", "Criminal Justice");
INSERT INTO professors(name,department) VALUES ("Elizabeth Lederer", "History");
INSERT INTO professors(name,department) VALUES ("Odin Branch", "Science");
INSERT INTO professors(name,department) VALUES ("Martha Lacy", "Film and Media");
INSERT INTO professors(name,department) VALUES ("Leanne Chambers", "Science");
INSERT INTO professors(name,department) VALUES ("Garrett Coyne", "Film and Media");
INSERT INTO professors(name,department) VALUES ("Elliot Anderson", "Language");
INSERT INTO professors(name,department) VALUES ("Reggie Davis", "English");
INSERT INTO professors(name,department) VALUES ("Duvan Araga", "Business");
INSERT INTO professors(name,department) VALUES ("Eloise Anderson", "Arts and Music");
INSERT INTO professors(name,department) VALUES ("Rick Reynolds", "Language");
INSERT INTO professors(name,department) VALUES ("David Sachs", "History");
INSERT INTO professors(name,department) VALUES ("Marshall Malloy", "Business");
INSERT INTO professors(name,department) VALUES ("Angel Martin", "Math and Statistics");
INSERT INTO professors(name,department) VALUES ("Matt Miller", "Film and Media");
INSERT INTO professors(name,department) VALUES ("James Jenkin", "Criminal Justice");
INSERT INTO professors(name,department) VALUES ("Dani Trant", "Language");
INSERT INTO professors(name,department) VALUES ("Evelyn Williams", "History");
INSERT INTO professors(name,department) VALUES ("Vanessa Lutz", "Buisness");
INSERT INTO professors(name,department) VALUES ("Ivy Miller", "Science");
INSERT INTO professors(name,department) VALUES ("Lauren Scott", "English");
INSERT INTO professors(name,department) VALUES ("Carrie Davis", "Math and Statistics");
INSERT INTO professors(name,department) VALUES ("Susan Murphy", "Film and Media");
INSERT INTO professors(name,department) VALUES ("Harry Ross", "History");
INSERT INTO professors(name,department) VALUES ("Barney Stinson", "Political Science");
INSERT INTO professors(name,department) VALUES ("Ted Mosby", "Political Science");
INSERT INTO professors(name,department) VALUES ("Robin Schmidt", "Political Science");
INSERT INTO professors(name,department) VALUES ("Lily Aldrin", "Political Science");
INSERT INTO professors(name,department) VALUES ("Luke Mosby", "Political Science");
INSERT INTO professors(name,department) VALUES ("Ranjit Singh", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Wendy Erickson", "Computer Science");
INSERT INTO professors(name,department) VALUES ("James Stinson", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Zoey Pearson", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Marvin Erickson", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Quin Garvey", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Ssandy Rivers", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Stella Zinman", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Arthur Hobbs", "Computer Science");
INSERT INTO professors(name,department) VALUES ("Rachel Green", "Economics");
INSERT INTO professors(name,department) VALUES ("Monica Gellar", "Economics");
INSERT INTO professors(name,department) VALUES ("Kabir Khan", "Economics");
INSERT INTO professors(name,department) VALUES ("Paulo Costanzo", "Economics");
INSERT INTO professors(name,department) VALUES ("Andrea Anders", "Economics");
INSERT INTO professors(name,department) VALUES ("Gina Tribbiani", "Economics");
INSERT INTO professors(name,department) VALUES ("Alex Garret", "Education");
INSERT INTO professors(name,department) VALUES ("Micheal Tribbiani", "Education");
INSERT INTO professors(name,department) VALUES ("Zach Miller", "Education");
INSERT INTO professors(name,department) VALUES ("Joseph Francis", "Education");
INSERT INTO professors(name,department) VALUES ("Chandler Bing", "Dance");
INSERT INTO professors(name,department) VALUES ("Matt Garret", "Dance");
INSERT INTO professors(name,department) VALUES ("Matthew Perry", "Dance");
INSERT INTO professors(name,department) VALUES ("Phoebe Hannigan", "Education");
INSERT INTO professors(name,department) VALUES ("Tate Langdon", "Education");
INSERT INTO professors(name,department) VALUES ("Audrey Tindall", "Education");
INSERT INTO professors(name,department) VALUES ("Shelby Miller", "Accounting");
INSERT INTO professors(name,department) VALUES ("Sally Howard", "Religion");
INSERT INTO professors(name,department) VALUES ("Lana Winters", "Religion");
INSERT INTO professors(name,department) VALUES ("Zachary Quinto", "Religion");
INSERT INTO professors(name,department) VALUES ("Jessica Lange", "History");
INSERT INTO professors(name,department) VALUES ("Dandy Mott", "History");
INSERT INTO professors(name,department) VALUES ("John Carrol", "History");
INSERT INTO professors(name,department) VALUES ("Violet Harmen", "History");
INSERT INTO professors(name,department) VALUES ("Aaron Smith", "History");
INSERT INTO professors(name,department) VALUES ("Jonathan Johnson", "Accounting");
INSERT INTO professors(name,department) VALUES ("Robert Williams", "Accounting");
INSERT INTO professors(name,department) VALUES ("Carson Brown", "Psychology");
INSERT INTO professors(name,department) VALUES ("Adam Jones", "Psychology");
INSERT INTO professors(name,department) VALUES ("Ian Miller", "Psychology");
INSERT INTO professors(name,department) VALUES ("Jordan Johnson", "Psychology");
INSERT INTO professors(name,department) VALUES ("Jason Davis", "Psychology");
INSERT INTO professors(name,department) VALUES ("Thomas Smith", "Psychology");
INSERT INTO professors(name,department) VALUES ("Leo Anderson", "Psychology");
INSERT INTO professors(name,department) VALUES ("Charles Wilson", "Psychology");
INSERT INTO professors(name,department) VALUES ("Christian Anderson", "Psychology");
INSERT INTO professors(name,department) VALUES ("Theodore Wilson", "Humanities");
INSERT INTO professors(name,department) VALUES ("Nathan Jones", "Humanities");
INSERT INTO professors(name,department) VALUES ("Lincoln Miller", "Humanities");
INSERT INTO professors(name,department) VALUES ("Joshua Wilson", "Humanities");
INSERT INTO professors(name,department) VALUES ("Andrew Taylor ", "Humanities");
INSERT INTO professors(name,department) VALUES ("Matthew Davis", "Language");
INSERT INTO professors(name,department) VALUES ("Joseph Miller", "Language");
INSERT INTO professors(name,department) VALUES ("James Smith", "Language");
INSERT INTO professors(name,department) VALUES ("Samuel Johnson", "Language");
INSERT INTO professors(name,department) VALUES ("Daniel Davis", "Language");
INSERT INTO professors(name,department) VALUES ("Benjamin Anderson", "History");
INSERT INTO professors(name,department) VALUES ("Oliver Jones", "History");
INSERT INTO professors(name,department) VALUES ("Mason Lee", "Science");
INSERT INTO professors(name,department) VALUES ("Henry Lee", "Science");
INSERT INTO professors(name,department) VALUES ("Jackson Wang", "Law");
INSERT INTO professors(name,department) VALUES ("William Smith", "English");
INSERT INTO professors(name,department) VALUES ("Lucas Taylor ", "English");
INSERT INTO professors(name,department) VALUES ("Liam Johnson", "English");


DELETE FROM professors where professor_id = 1;

