#500 entries for this student table minimum start at 5000
INSERT INTO students(first_name,last_name,major,minor) VALUES ("John", "Smith", "English", "Computer Science");
ALTER TABLE students AUTO_INCREMENT = 1000;

INSERT INTO students(first_name,last_name,major,minor) VALUES ("John", "Smith", "English", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Matt", "Smith", "Dance", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("David", "Tennant", "Physics", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Clara", "Oswald", "English", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jenny", "Copper", "Media", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Bob", "Smith", "Psychology", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Amy", "Pond", "Humanities", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Emily", "Thompson", "Chemistry", "Geography");
INSERT INTO students(first_name,last_name,major) VALUES ("Billy", "Joe", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rory", "Pond", "Nursing", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Martha", "Jones", "Biology", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Donna", "Noble", "Media", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("River", "Song", "Archeology", "Anthropology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jackie", "Tyler", "Art", "Music");
INSERT INTO students(first_name,last_name,major) VALUES ("Mickey", "Simth", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jack", "Harkness", "Business", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Wilfred", "Mott", "History", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Adrian", "Monk", "Criminology", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Leland", "Stottlemeyer", "Criminal Law", "Criminology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Randall", "Disher", "Criminology", "Theater");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Natalie", "Teeger", "Accounting", "Spanish");
INSERT INTO students(first_name,last_name,major) VALUES ("Sharona", "Fleming", "Nursing");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Trudy", "Jackson", "English", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Meridith", "Grey", "Biology", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Miranda", "Bailey", "Computer Science", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Richard", "Weber", "Anthropology", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Alex", "Karev", "Math", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Owen", "Hunt", "History", "Geogrpahy");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jackson", "Avery", "Geology", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Derek", "Shepherd", "Neuroscience", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Callie", "Torres", "Humanities", "Urban Studies");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Arizona", "Robins", "Education", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Cristina", "Yang", "Political Science", "Urban Studies");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("April", "Kepner","Religion", "Humanities");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jo", "Wilson", "Chemisty", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Maggie", "Pierce", "Philosophy", "Religion");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Amelia", "Shepherd", "Music", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mark", "Sloan", "Economics", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ben", "Warren", "Statistics", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Isabel", "Stevens", "Education", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Andrew", "Decluca", "Education", "Italian");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Stephanie", "Edwards", "Physics", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Teddy", "Altman", "Business", "Political Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("George", "OMalley", "Sociology", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Catherine", "Fox", "Media", "Business");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Preston", "Burke", "Accounting", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Addison", "Montgomery", "Environmental Studies", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Levi", "Schmitt", "Computer Science", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nathan", "Roggs", "Media", "Theater");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Shane", "Ross", "Geography", "Enivronmental Studies");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Leah", "Murphy", "French", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Thomas", "Koracick", "Archaeology", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Atticus", "Lincoln", "History", "Political Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Carina", "Deluca", "Economics", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Casey", "Parker", "Anthropology", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nico", "Kim", "Statistics", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Erica", "Hahn", "Spanish", "Urban Studies");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Denny", "Duquette", "Italian", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Adele", "Webber", "Nursing", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Heather", "Brooks", "Psychology", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Penelope", "Blake", "Philosophy", "Religion");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Olivia", "Harper", "Physics", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Matthew", "Taylor", "Chemistry", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Lexi", "Grey", "Biology", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Henry", "Burton", "Nutrition", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nicole", "Herman", "Biology", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Charles", "Percy", "Religion", "Philosophy");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sam", "Bello", "Spanish", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Eliza", "Minnick", "Accounting", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Reed", "Adamson", "English", "Latin");
INSERT INTO students(first_name,last_name,major) VALUES ("Shawn", "Spencer", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Burton", "Guster", "Chemistry", "Business");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Carlton", "Lassiter", "Criminology", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Juliet", "OHara", "Criminology", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Henry", "Spencer", "Philosophy", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Karen", "Vick", "Criminal Law", "Criminology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Buzz", "McNab", "Criminology", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Woody", "Strode", "Biology", "Humanities");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Pierre", "Desperaux", "Art", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Temperance", "Brennan", "Anthropology", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Seeley", "Booth", "Criminology", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Angela", "Montenegro", "Art", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jack", "Hodgins", "Nutrition", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Camile", "Saroyan", "Math", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Lance", "Sweets", "Psychology", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Zack", "Addy", "Math", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("James", "Aubrey", "Criminology", "Nutrition");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Caroline", "Julian", "Criminal Law", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Wendell", "Bray", "Geology", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Clark", "Edison", "Anthropology", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Daisy", "Wick", "Accounting", "Religion");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Arastoo", "Varziri", "Education", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Max", "Keenan", "Political Science", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Daniel", "Goodman", "Archeaologist", "Geography");
INSERT INTO students(first_name,last_name,major) VALUES ("Colin", "Fisher", "Geology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Parker", "Booth", "English", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Vincent", "Murray", "History", "Philosophy");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jessica", "Warren", "Media", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Michelle", "Warren", "Urban Studies", "Political Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rodolfo", "Fuentes", "Spanish", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Oliver", "Wells", "Physics", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Finn", "Abernathy", "Italian", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gordon", "Wyatt", "Psychology", "Nutrition");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Hannah", "Burley", "Media", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nancy", "Taylor", "Statistics", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Melissa", "Barton", "Biology", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Fanny", "Anderson", "Economics", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sammy", "Samson", "Spanish", "Political Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Simon", "Brown", "Computer Science", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Vicky", "Jones", "Religion", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Vincent", "Miller", "Biology", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Becky", "Davis", "Physics", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Anthony", "Wilson", "Psychology", "Nursing");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Anatasia", "Johnson", "Chemistry", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Lily", "Gonzalez", "History", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kelly", "Kim", "English", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("William", "Gomez", "Accounting", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Eric", "Lopez", "Dance", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Andy", "Chen", "Physics", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Benjamin", "Wang", "Math", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mandy", "Zhang", "Statistics", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jacob", "John", "Computer Science", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jake", "Brown", "Music", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Charles", "Wolf", "Education", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Joseph", "Lee", "Biology", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Micheal", "Li", "Biology", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mike", "Singh", "Philisophy", "Geography");
INSERT INTO students(first_name,last_name,major) VALUES ("Jimmy", "Lee", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ashley", "Zhang", "Physics", "Japanese");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jackson", "Chen", "Chinese", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Junior", "Cheung", "Spanish", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mark", "Brown", "Statistics", "French");
INSERT INTO students(first_name,last_name,major) VALUES ("Tiffany", "Singh", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Abraham", "Wong", "Religion", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Abby", "Wang", "Economics", "Latin");
INSERT INTO students(first_name,last_name,major) VALUES ("Aaron", "Gomez", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Alex", "Barton", "Nursing", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Anson", "Lopez", "Psychology", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Ada", "Sampson", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Bambi", "Cheung", "Media", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Barbara", "Taylor", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Barbie", "Kim", "English", "Chinese");
INSERT INTO students(first_name,last_name,major) VALUES ("Cindy", "Park", "Biology");
INSERT INTO students(first_name,last_name,major) VALUES ("David", "Xu", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Edward", "Wu", "German", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Edwin", "Jones", "Dance", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sam", "Liu", "History", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Fred", "Miller", "Latin", "Biology");
INSERT INTO students(first_name,last_name,major) VALUES ("Jimmy", "Davis", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sally", "Smith", "Math", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("James", "Wilson", "French", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Fanny", "Miller", "Religion", "Film");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Tracy", "Lee", "Chinese", "Japanese");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Hannah", "Chen", "German", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Halsey", "Wang", "Statistics", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Harmoney", "Jung", "Japanese", "Education");
INSERT INTO students(first_name,last_name,major) VALUES ("Casey", "Kim", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Cathy", "Min", "Accounting", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Katie", "Zhang", "Chemistry", "Nutrition");
INSERT INTO students(first_name,last_name,major) VALUES ("Jenny", "Min", "French");
INSERT INTO students(first_name,last_name,major) VALUES ("Lisa", "Chen", "Japanese");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Timmy", "Cheung", "Chinese", "Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Timothy", "Wong", "English", "Criminology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Minnie", "Wang", "Nursing", "Chemistry");
INSERT INTO students(first_name,last_name,major) VALUES ("Mandy", "Park", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sandy", "Wilson", "Latin", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Moon", "Williams", "Accounting", "Business");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nicky", "Davis", "Business", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Joe", "Drew", "Art", "French");
INSERT INTO students(first_name,last_name,major) VALUES ("Kevin", "Swan", "Nutrition");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kenny", "Xu", "Criminal Law", "Business");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("David", "Wu", "Law", "History");
INSERT INTO students(first_name,last_name,major) VALUES ("Danny", "Zhang", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ralph", "Lee", "Chemistry", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kitty", "Kim", "Physics", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Coco", "Park", "Statistics", "Psychology");
INSERT INTO students(first_name,last_name,major) VALUES ("Angel", "Min", "Law");
INSERT INTO students(first_name,last_name,major) VALUES ("May", "Jung", "Business");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("April", "Taylor", "Art", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("June", "Miller", "Dance", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Emily", "Johnson", "Music", "Japanese");
INSERT INTO students(first_name,last_name,major) VALUES ("Gabriella", "Smith", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gabby", "Yang", "Italian", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jasmine", "Yueng", "French", "Spanish");
INSERT INTO students(first_name,last_name,major) VALUES ("Bobby", "Li", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dexter", "Barton", "Spanish", "English");
INSERT INTO students(first_name,last_name,major) VALUES ("Hilary", "Miller", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Miley", "Sampson", "Chinese", "Korean");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nora", "Cyrus", "Italian", "Statistics");
INSERT INTO students(first_name,last_name,major) VALUES ("Nancy", "Xu", "Criminal Law");
INSERT INTO students(first_name,last_name,major) VALUES ("Melody", "Chen", "Business");
INSERT INTO students(first_name,last_name,major) VALUES ("Martin", "Gonzalez", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Candy", "Taylor", "Statistics", "Korean");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sammie", "Wilson", "Nutrition", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Billy", "Xu", "Business", "Law");
INSERT INTO students(first_name,last_name,major) VALUES ("Erica", "Wong", "Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Eric", "Chen", "Criminal Law", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Melissa", "Park", "Math", "Korean");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Carmen", "Kim", "Biology", "Japanese");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Flora", "Cyrus", "Chemistry", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Francesca", "Jung", "Korean", "Japanese");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Fanny", "Lee", "Chinese", "Korean");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Danny", "Chen", "Japanese", "Chinese");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kimmy", "Cheung", "Italian", "French");
INSERT INTO students(first_name,last_name,major) VALUES ("Kenny", "Zhang", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ken", "Wu", "History", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Simon", "Willams", "Computer Science", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Vincent", "Byant", "Economics", "Accounting");
INSERT INTO students(first_name,last_name,major) VALUES ("Vicky", "Gao", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ricky", "Li", "History", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Amy", "Zhang", "Media", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Amelia", "Cheung", "Music", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jim", "Ng", "Dance", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rose", "Barton", "Biology", "Business");
INSERT INTO students(first_name,last_name,major) VALUES ("Roslie", "Miller", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Wendy", "Smith", "Music", "Nutrition");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Joy", "Lopez", "Korean", "Italian");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Salma", "Gomez", "Spanish", "English");
INSERT INTO students(first_name,last_name,major) VALUES ("Megan", "Samson", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Selena", "Lee", "Law", "Business");
INSERT INTO students(first_name,last_name,major) VALUES ("Nancy", "Drew", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kevin", "Chen", "Business", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sanah", "Grey", "Computer Science", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gabriela", "Simmons", "Media", "Art");
INSERT INTO students(first_name,last_name,major) VALUES ("Ramone", "Dolan", "Media");
INSERT INTO students(first_name,last_name,major) VALUES ("Charlton", "Miller", "Undeclared");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ingo", "Bernard", "Math", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Parris", "Ryan", "Statistics", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Thomas", "Appleton", "Accounting", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Shannon", "Woodley", "Economics", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Christiano", "Stubbs", "Accounting", "Economics");
INSERT INTO students(first_name,last_name,major) VALUES ("Kady", "Villa", "Undeclared");
INSERT INTO students(first_name,last_name,major) VALUES ("Blade", "Moreno", "Social Work");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Esma", "Paine", "English", "History");
INSERT INTO students(first_name,last_name,major) VALUES ("Tara", "Maguire", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Elora", "Spears", "Psychology", "Sociology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Leen", "Sykes", "Sociology", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Frances", "Roche", "Psychology", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Maddy", "Bull", "French", "History");
INSERT INTO students(first_name,last_name,major) VALUES ("Susie", "Brett", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Helen", "Cannon", "Undeclared");
INSERT INTO students(first_name,last_name,major) VALUES ("Sapphire", "Pratt", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kurtis", "Myers", "Psychology", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Franklin", "Levy", "Computer Science", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Bilal", "House", "Math", "Statistics");
INSERT INTO students(first_name,last_name,major) VALUES ("Gregor", "Montes", "Psychology");
INSERT INTO students(first_name,last_name,major) VALUES ("Jonathan", "Berg", "Undeclared");
INSERT INTO students(first_name,last_name,major) VALUES ("Sumaiyah", "Wall", "Urban Studies");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jackson", "Pineda", "Economics", "Accounting");
INSERT INTO students(first_name,last_name,major) VALUES ("Milana", "Corbett", "Undeclared");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Scarlett", "Dunne", "Biology", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Kimberly", "Leonard", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Lindsey", "Ryder", "Chemistry", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Colin", "Hopkins", "Computer Science", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Edgar", "Lam", "Media", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Tarik", "Lake", "Undeclared");
INSERT INTO students(first_name,last_name,major) VALUES ("Elina", "Hodges", "Social Work");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Deniz", "Stein", "Dance", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Arwen", "Bray", "Music", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Allison", "Silva", "Psychology", "Sociology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mina", "Berry", "Sociology", "Psychology");
INSERT INTO students(first_name,last_name,major) VALUES ("Lorna", "Erickson", "Undeclared");
INSERT INTO students(first_name,last_name,major) VALUES ("Omar", "Larson", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kellie", "Wallis", "French", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Hakeem", "Bowen", "Dance", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Grace", "Mercado", "Chinese", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rahim", "Plant", "Computer Science", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Shaan", "Craft", "Media", "Film");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Chad", "Peck", "Art", "Dance");
INSERT INTO students(first_name,last_name,major) VALUES ("Saffa", "Steele", "Undeclared");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Farah", "Hughes", "Media", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Shawn", "Jonhson", "Undeclared");
INSERT INTO students(first_name,last_name,major) VALUES ("Tyler", "Ali", "Social Work");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Hans", "Mccarty", "Art", "Media");
INSERT INTO students(first_name,last_name,major) VALUES ("Ikra", "Henry", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Virgil", "Rogers", "Dance", "Sociology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Cara", "Soto", "Urban Studies", "Public Policy");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jannat", "Bridges", "Math", "Statistics");
INSERT INTO students(first_name,last_name,major) VALUES ("Zaydan", "Knight", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Shedlon", "Stewart", "Chinese", "History");
INSERT INTO students(first_name,last_name,major) VALUES ("Neil", "Mckee", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Marek", "Ritter", "English", "History");
INSERT INTO students(first_name,last_name,major) VALUES ("Levi", "Bullock", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Calvin", "Page", "Psychology", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Pearl", "Goodman", "Computer Science", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Finn", "Redfern", "Media", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Reya", "Hooper", "Undeclared");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Roisin", "Mcinney", "Sociology", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Shayan", "Avery", "Psychology", "Sociology");
INSERT INTO students(first_name,last_name,major) VALUES ("Findlay", "Hodges", "Undeclared");
INSERT INTO students(first_name,last_name,major) VALUES ("Naomi", "Gill", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Millicent", "Grimes", "Statistics", "Math");
INSERT INTO students(first_name,last_name,major) VALUES ("Shahid", "Alston", "Biology");
INSERT INTO students(first_name,last_name,major) VALUES ("Henry", "Carson", "Chemistry");
INSERT INTO students(first_name,last_name,major) VALUES ("Zahra", "Jones", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Caden", "Lacey", "Accounting", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Can", "Wiggens", "Economics", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Pamela", "Gunn", "Bioinformatics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Safa", "Truong", "Computer Science", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jena", "Odom", "Media", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rodney", "Medina", "Classical Studies", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Coral", "Ayala", "Creative Writing", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Eduardo", "Vance", "English", "Creative Writing");
INSERT INTO students(first_name,last_name,major) VALUES ("Abiha", "Milner", "Earth Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Emily", "Lozano", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Alaya", "Pierce", "Film", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Orion", "Stone", "Media", "Film");
INSERT INTO students(first_name,last_name,major) VALUES ("Elias", "Macias", "Education");
INSERT INTO students(first_name,last_name,major) VALUES ("Dale", "Fulton", "Education");
INSERT INTO students(first_name,last_name,major) VALUES ("Holli", "Richardson", "Education");
INSERT INTO students(first_name,last_name,major) VALUES ("Komal", "Stevenson", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ayra", "Stevens", "Education", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Melody", "Berg", "Psychology", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ashraf", "McGregor", "Computer Science", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jamel", "Odom", "Economics", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Irene", "Melendez", "Dance", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Airah", "Allen", "Film", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Janet", "Rutledge", "Media", "Film");
INSERT INTO students(first_name,last_name,major) VALUES ("Darcy", "Turnbell", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Paola", "Morse", "Media", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Shea", "Rigby", "Computer Science", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Martha", "Booth", "Accounting", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kendal", "English", "Math", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Lainey", "Vega", "Statistics", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Bear", "Salt", "English", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Luisa", "Chester", "Psychology", "Sociology");
INSERT INTO students(first_name,last_name,major) VALUES ("Gabriel", "Kirby", "Undeclared");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Orla", "McCool", "English", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Louisa", "Harland", "Psychology", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Clare", "Devlin", "Math", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nicola", "Coughlan", "Media", "Journalism");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jenny", "Joyce", "Physics", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Leah", "Orourke", "Geology", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Erin", "Quinn", "English", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Saoirse", "Jackson", "Religion", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Michelle", "Mallon", "Nursing", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jamie", "Donnel", "Music", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("James", "Maguire", "Art", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dylan", "Llewellyn", "Political Science", "International Relations");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("David", "Donnelly", "Statistics", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Anthony", "Boyle", "French", "Sociology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kathy", "Clark", "History", "Political Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Tara", "Lynne", "Chemistry", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ian", "McElhinney", "Biology", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Tommy", "Tiernan", "History", "Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("David", "Rose", "Chemistry", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dan", "Levi", "Media", "Film");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Stevie", "Budd", "English", "Russian");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Alexis", "Bose", "Media", "Journalism");
INSERT INTO students(first_name,last_name,major) VALUES ("Moira", "Rose", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sarah", "Levy", "History", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Twyla", "Sands", "Nursing", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Annie", "Murphy", "Psychology", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Emily", "Hampshire", "Pyschology", "Anthropology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ted", "Mullens", "Geography", "Geology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dustin", "Milligan", "Geology", "Physics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Catherine", "Ohara", "Statistics", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mutt", "Schmitt", "Art", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Tim", "Rozon", "Physics", "Nursing");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Bob", "Currie", "Spanish", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("John", "Hemphill", "Political Science", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Chris", "Elliot", "Music", "Philosphy");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Roland", "Smitt", "Media", "Film");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ronnie", "Lee", "French", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Karen", "Robinson", "Physics", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jocelyn", "Smit", "History", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Johnny", "Rose", "Media", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Eugene", "Levy", "Economics", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Wendy", "Kurtz", "Dance", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Robin", "Duke", "Music", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Patrick", "Lutz", "Geography", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Noah", "Reid", "Biology", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Julia", "Dreyfus", "Law", "International Relations");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Selina", "Meyer", "Political Science", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Anna", "Chlumsky", "Criminal Law", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Amy", "Brookheimer", "Cybersecurity", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Tony", "Hale", "Journalism", "Political Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gary", "Walsh", "English", "Creative Writing");
INSERT INTO students(first_name,last_name,major) VALUES ("Timothy", "Simmons", "Nursing");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jonah", "Ryan", "Media", "Journalism");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Matt", "Walsh", "Chemistry", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mike", "McLintok", "Educaction", "Anthropology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Reid", "Scott", "Statistics", "Journalism");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dan", "Egan", "Math", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sam", "Richardson", "English", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Richard", "McQuigg", "Political Theory", "Internaitonal Relations");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gary", "Cole", "Biology", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kevin", "Dunn", "Chemistry", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ben", "Cafferty", "Biology", "Education");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sarah", "Sutherland", "Women and Gender Studies", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Catherine", "Meyer", "Media", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Clea", "DuVall", "Education", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Marjorie", "Palmiotti", "Journalism", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sufe", "Bradshaw", "Education", "Journalism");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sue", "Wilson", "Nursing", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dan", "Bakkedahl", "Media", "Criminal Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Paul", "Scheer", "Journalism", "International Relations");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Stevie", "Smith", "Chemistry", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Peter", "MacNicol", "Economics", "Journalism");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jeff", "Kane", "English", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Margaret", "Colin", "Math", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Jane", "McCabe", "Political Science", "Pre-Law");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Nelson", "Franklin", "Education", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Will", "Henderson", "Statistics", "Political Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Phil", "Reeves", "Math", "Geology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Randall", "Park", "Political Science", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Danny", "Chung", "Media", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sally", "Phillips", "English", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Minn", "Hakkinen", "Political Science", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Eugene", "Alper", "Geology", "Anthropology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Stephen", "Fry", "Media", "Journalism");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Diedrich", "Bader", "English", "Economics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Peter", "Banifaz", "Computer Science", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kathy", "Najimy", "Political Science", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Andrew", "Leeds", "English", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Julia", "Mamone", "Biology", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Samantha", "Helmy", "Biology", "Pre-Med");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sarah", "Decker", "Education", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Molly", "Baran", "Political Science", "Human Rights");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Kirsten", "Ebenezer", "Political Science", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Felice", "Gross", "Dance", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Marcie", "Jacob", "Sociology", "Anthropology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Emily", "Perry", "Geology", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Erin", "Brown", "English", "Anthropology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Angela", "Toner", "Chemistry", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Lauren", "Bolen", "Media", "Journalism");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Humna", "Elahi", "Chemistry", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Teddy", "Lupin", "English", "Statistics");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Remus", "Lupin", "History", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Xenophillius", "Lovegood", "Media", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Luna", "Lovegood", "Math", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Neville", "Longbottom", "English", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Augusta", "Longbottom", "Statistics", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Frank", "Longbottom", "History", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Alice", "Longbottom", "English", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gilderoy", "Lockhart", "Accounting", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rudolphus", "Lestrange", "Psychology", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rabastan", "Lestrange", "Biology", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Bellatrix", "Lestrange", "Spanish", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Silvanus", "Kkettleburn", "German", "Geology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Viktor", "Krum", "Statistics", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Igor", "Karkaroff", "English", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Lee", "Jordan", "Biology", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Angelina", "Johnson", "Accounting", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mofalda", "Hopkirk", "Genetics", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rolanda", "Hooch", "Psychology", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Rubeius", "Hagrid", "English", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gellert", "Grindelwart", "Computer Science", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Fenrir", "Greyback", "Geology", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Hermione", "Granger", "History", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gregory", "Gyle", "Chemistry", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Anthony", "Goldstien", "Urban Studies", "Accounting");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Cornelius", "Fudge", "English", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Florean", "Fortescue", "Geology", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Filius", "Flitwick", "Math", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Mundungus", "Fetcher", "Biology", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Seamus", "Finnigan", "Geology", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Justin", "Finch", "Urban Studies", "Geography");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Argus", "Filch", "Biology", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Arabella", "Fig", "English", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Marietta", "Edgecomb", "Political Science", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Vernon", "Dersley", "Math", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Petunia", "Dersley", "Genetics", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Marge", "Dursley", "History", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dudley", "Dursely", "Political Science", "Philosophy");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ariana", "Dumbledore", "Theatre", "Religion");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Albus", "dumbledore", "Math", "History");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Aberforth", "Dumbledore", "Political Science", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gideon", "Prewett", "German", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Antonin", "Dolohov", "English", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Elphias", "Doge", "Urban studies", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Cedric", "Diggory", "Philosophy", "Math");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dedalus", "Diggory", "Computer Science", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Fleur", "Delacour", "Dance", "Computer Science");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Amos", "Digory", "Psychology", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Gabby", "Delacour", "Math", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("John", "Dawlish", "Religion", "Theatre");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Barty", "Crouch", "Theatre", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dean", "Thomas", "Art", "Urban Studies");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Denis", "Creevy", "Philosophy", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Dirk", "Cresswell", "Physics", "Chemistry");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Colin", "Creevy", "Music", "Dance");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Micheal", "Connor", "Spanish", "Sociology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Percy", "Weasley", "Media", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Tom", "Riddle", "Public Policy", "Latin");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ron", "Weasley", "Dance", "Psychology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Severus", "Snape", "Anthropology", "Music");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Frank", "Bryce", "Physics", "Religion");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Terry", "Boot", "Philosophy", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Amelia", "Bones", "Biology", "Spanish");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Sirius", "Black", "English", "Art");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Katie", "Bell", "English", "Biology");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Bathilda", "Bagshot", "History", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Ludo", "Bagman", "Physics", "English");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Hannah", "Abbot", "Accounting", "French");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Shawn", "Shakir", "Computer Science", "Media");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Hans", "Abbott", "Art", "Media");
INSERT INTO students(first_name,last_name,major) VALUES ("Tyler", "Sampson", "Social Work");
INSERT INTO students(first_name,last_name,major,minor) VALUES ("Saqib", "Orr", "Statistics", "Computer Science");
INSERT INTO students(first_name,last_name,major) VALUES ("Zaid", "Mack", "Undeclared");

DELETE FROM students where student_id = 1;




